# Created using winget manifest generator
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: cameronrye.clarissa
PackageVersion: 1.3.0
InstallerType: portable
Commands:
  - clarissa
NestedInstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cameronrye/clarissa/releases/download/v1.3.0/clarissa-windows-x64.exe
    InstallerSha256: F5BAA02606D4466B1C78803AD6FC45D799A11D4D4D554D9099761A0617FD2718
    NestedInstallerFiles:
      - RelativeFilePath: clarissa-windows-x64.exe
        PortableCommandAlias: clarissa
ManifestType: installer
ManifestVersion: 1.6.0

